language: python
python:
  - '2.7'

jobs:
  include:
    - stage: test
      install:
        - pip install -r requirements.txt
        - pip install nose2 coverage
      script:
        - nose2 -v --with-coverage --coverage-report term-missing

    - stage: deploy
      install:
        # Install latest img binary
        - curl -fsSL https://github.com/genuinetools/img/releases/download/v0.4.7/img-linux-amd64 -o img
        # Verify the sha256sum
        - export SHASUM=$(curl -fsSL https://github.com/genuinetools/img/releases/download/v0.4.7/img-linux-amd64.sha256 | awk '{ print $1 }')
        - if [ "$SHASUM" != "$(shasum -a 256 /usr/local/bin/img | awk '{ print $1 }')" ]; then echo "sha256sum mismatch!"; exit 1; fi
        - chmod a+x img
      script:
        - ./img build -t rycus86/try-img .
      after_success:
        - echo ${DOCKER_PASSWORD} | img login -u rycus86 -password-stdin
        - img push rycus86/try-img

