language: python
python:
  - '2.7'

jobs:
  include:
    - stage: test
      install:
        - pip install -r requirements.txt
        - pip install nose2 coverage
      script:
        - nose2 -v --with-coverage --coverage-report term-missing

    - stage: deploy
      addons:
        apt:
          packages:
            - uidmap
      install:
        # Install latest img binary
        - curl -fsSL https://github.com/genuinetools/img/releases/download/v0.4.7/img-linux-amd64 -o img
        # Verify the sha256sum
        - export SHASUM=$(curl -fsSL https://github.com/genuinetools/img/releases/download/v0.4.7/img-linux-amd64.sha256 | awk '{ print $1 }')
        - if [ "$SHASUM" != "$(shasum -a 256 img | awk '{ print $1 }')" ]; then echo "sha256sum mismatch!"; exit 1; fi
        - chmod a+x img
        # set up runc
        - curl -fsSL -o runc https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64 && chmod +x runc
        - PATH=`pwd`:$PATH runc --version
        - PATH=`pwd`:$PATH IMG_DISABLE_EMBEDDED_RUNC=1 img version
      script:
        - PATH=`pwd`:$PATH IMG_DISABLE_EMBEDDED_RUNC=1 ./img build -t rycus86/try-img .
      after_success:
        - echo ${DOCKER_PASSWORD} | img login -u rycus86 -password-stdin
        - img push rycus86/try-img

